services:
  mydb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - vipdb:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080

  lunch:
    build: .
    image: lunch:v7
    environment:
    - TITLE=lunchtime for lalyos [dev]
    - COLOR=lightblue
    ports:
    - 80
  coffee:
    build: .
    image: lunch:v7
    environment:
    - TITLE=Coffe for lalyos [dev]
    - COLOR=hotpink
    ports:
    - 80

volumes:
  vipdb:
