services:
  mydb:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - vipdb:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080


  redis:
    profiles:
      - prod
    build: .
    image: lunch:v7
    environment:
    - TITLE=redis
    - COLOR=zellow
    ports:
    - 80

  coffee:
    build: .
    image: lunch:v7
    environment:
    - TITLE=${TITLE:-Default kompoze}
    - COLOR=${COLOR:-yellow}
    labels:
      - traefik.frontend.auth.basic=admin:$$1$$I5Kt8BwT$$G4y6mBV3xVzyZKUECxqV61
    ports:
    - 80

volumes:
  vipdb:

networks:
  default:
    name: proxy