services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - --retry
      - --rest
      - --docker.domain=${DOMAIN:-lvh.me}
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.lvh.me"
      - "traefik.port=8080"
    ports:
    - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mydb:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - vipdb:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080

  coffee:
    build: .
    image: lunch:v7
    environment:
    - TITLE=${TITLE:-Default kompoze}
    - COLOR=${COLOR:-yellow}
    ports:
    - 80

volumes:
  vipdb:
