services:
  proxy:
    image: nginxproxy/nginx-proxy
    ports:
    - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  mydb:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - vipdb:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    environment:
    - VIRTUAL_HOST=adminer.lvh.me
    ports:
      - 8080

  coffee:
    build: .
    image: lunch:v7
    environment:
    - TITLE=${TITLE:-Default kompoze}
    - COLOR=${COLOR:-yellow}
    - VIRTUAL_HOST=coffee.lvh.me
    ports:
    - 80

volumes:
  vipdb:
