services:
  mydb:
    image: postgres:16.1
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - vipdb:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080

  coffee:
    build: .
    image: lunch:v7
    environment:
    - TITLE=${TITLE:-Default kompoze}
    - COLOR=${COLOR:-yellow}
    ports:
    - 80

volumes:
  vipdb:

networks:
  default:
    name: proxy